language: scala
scala:
  - 2.12.1
  - 2.11.8  
jdk:
  - oraclejdk8
sudo: false
services:
  - rabbitmq
notifications:
  slack: thenewmotion:AXSluctig1mmZbeKRDeeY41s
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
